# The URL the site will be built for
base_url = "https://joakim-taule-kartveit.no/food-recipes"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "no"

[search]
index_format = "elasticlunr_javascript"
include_title = true
include_content = true

[markdown]

[extra]
# Put all your custom variables here
